version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bank-db
    restart: always
    environment:
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
      POSTGRES_DB: bankdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  account-svc:
    build: ./account-svc
    container_name: account-service
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: bankuser
      DB_PASSWORD: bankpass
      DB_NAME: bankdb
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  pgdata:
