apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bank-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  ingressClassName: gce
  rules:
  - http:
      paths:
        - path: /healthz
          pathType: Prefix
          backend:
            service:
              name: bank-api
              port:
                number: 3000
        - path: /accountBalance
          pathType: Prefix
          backend:
            service:
              name: bank-api
              port:
                number: 3000
        - path: /addMoney
          pathType: Prefix
          backend:
            service:
              name: bank-api
              port:
                number: 3000
        - path: /transferMoney
          pathType: Prefix
          backend:
            service:
              name: bank-api
              port:
                number: 3000