apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: YmFua3Bhc3M=  # bankpass
  POSTGRES_USER: YmFua3VzZXI=      # bankuser
  POSTGRES_DB: YmFua2Ri            # bankdb